{
  "uid" : "34d49a7d3f9b8922",
  "name" : "验证输入密码不能为空测试用例",
  "fullName" : "testcases.test_all_case.TestALLAPI#test_test_login",
  "historyId" : "5f86f1ee1e626d36a249cef360e41d57",
  "time" : {
    "start" : 1673269292494,
    "stop" : 1673269292549,
    "duration" : 55
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: databases断言失败: 返回结果中没有:username",
  "statusTrace" : "self = <testcases.test_all_case.TestALLAPI object at 0x0000021A5CABD030>\ncaseinfo = {'extract': {'access_token': '\"access_token\":\"(.*?)\"', 'code': '$.code', 'username': '$.data.userInfo.username'}, 'fea...'json': {'password': '', 'type': 0, 'userName': 'chenjiawei132785'}, 'method': 'post', 'url': '/micro/ent/login'}, ...}\nbase_url = 'http://wanjidev.wandianzhang.com'\n\n    @pytest.mark.parametrize(\"caseinfo\", read_testcase(yaml_path))\n    # @pytest.mark.run(order=1)\n    def test_func(self, caseinfo, base_url):\n        allure.dynamic.feature(caseinfo['feature'])\n        allure.dynamic.story(caseinfo['story'])\n        allure.dynamic.title(caseinfo['title'])\n        if isinstance(caseinfo, list):  # 流程用例\n            for case in caseinfo:\n                allure.dynamic.title(case[\"title\"])\n                RequestUtil().standard_yaml_case(case, base_url)\n        else:  # 单接口用例\n            allure.dynamic.title(caseinfo[\"title\"])\n>           RequestUtil().standard_yaml_case(caseinfo, base_url)\n\ntestcases\\test_all_case.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommons\\request_util.py:71: in standard_yaml_case\n    assert_result(caseinfo['validate'], res)\ncommons\\assert_util.py:20: in assert_result\n    db_assert(value, res.json())\ncommons\\assert_util.py:91: in db_assert\n    raise_assert_error(\"databases断言失败: 返回结果中没有:\" + str(key) + \"\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmsg = 'databases断言失败: 返回结果中没有:username'\n\n    def raise_assert_error(msg):\n        logger.error(msg + \"\")\n        logger.info(\"----------测试用例*异常*结束----------\\n\")\n>       raise AssertionError(msg)\nE       AssertionError: databases断言失败: 返回结果中没有:username\n\ncommons\\assert_util.py:30: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "clear_extract_yaml",
    "time" : {
      "start" : 1673269291977,
      "stop" : 1673269291977,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "_verify_url",
    "time" : {
      "start" : 1673269291977,
      "stop" : 1673269291977,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  }, {
    "name" : "base_url",
    "time" : {
      "start" : 1673269291977,
      "stop" : 1673269291977,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: databases断言失败: 返回结果中没有:username",
    "statusTrace" : "self = <testcases.test_all_case.TestALLAPI object at 0x0000021A5CABD030>\ncaseinfo = {'extract': {'access_token': '\"access_token\":\"(.*?)\"', 'code': '$.code', 'username': '$.data.userInfo.username'}, 'fea...'json': {'password': '', 'type': 0, 'userName': 'chenjiawei132785'}, 'method': 'post', 'url': '/micro/ent/login'}, ...}\nbase_url = 'http://wanjidev.wandianzhang.com'\n\n    @pytest.mark.parametrize(\"caseinfo\", read_testcase(yaml_path))\n    # @pytest.mark.run(order=1)\n    def test_func(self, caseinfo, base_url):\n        allure.dynamic.feature(caseinfo['feature'])\n        allure.dynamic.story(caseinfo['story'])\n        allure.dynamic.title(caseinfo['title'])\n        if isinstance(caseinfo, list):  # 流程用例\n            for case in caseinfo:\n                allure.dynamic.title(case[\"title\"])\n                RequestUtil().standard_yaml_case(case, base_url)\n        else:  # 单接口用例\n            allure.dynamic.title(caseinfo[\"title\"])\n>           RequestUtil().standard_yaml_case(caseinfo, base_url)\n\ntestcases\\test_all_case.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommons\\request_util.py:71: in standard_yaml_case\n    assert_result(caseinfo['validate'], res)\ncommons\\assert_util.py:20: in assert_result\n    db_assert(value, res.json())\ncommons\\assert_util.py:91: in db_assert\n    raise_assert_error(\"databases断言失败: 返回结果中没有:\" + str(key) + \"\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmsg = 'databases断言失败: 返回结果中没有:username'\n\n    def raise_assert_error(msg):\n        logger.error(msg + \"\")\n        logger.info(\"----------测试用例*异常*结束----------\\n\")\n>       raise AssertionError(msg)\nE       AssertionError: databases断言失败: 返回结果中没有:username\n\ncommons\\assert_util.py:30: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "14de11b90fb6f7fe",
      "name" : "log",
      "source" : "14de11b90fb6f7fe.txt",
      "type" : "text/plain",
      "size" : 1193
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "登录模块"
  }, {
    "name" : "story",
    "value" : "登录接口"
  }, {
    "name" : "epic",
    "value" : "项目名称：万集接口自动化测试"
  }, {
    "name" : "parentSuite",
    "value" : "testcases"
  }, {
    "name" : "suite",
    "value" : "test_all_case"
  }, {
    "name" : "subSuite",
    "value" : "TestALLAPI"
  }, {
    "name" : "host",
    "value" : "DESKTOP-5ALEO36"
  }, {
    "name" : "thread",
    "value" : "4092-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_all_case"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "34d49a7d3f9b8922.json",
  "parameterValues" : [ ]
}